# Generated by Django 2.0.3 on 2019-08-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abnormalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_threshold', models.IntegerField(default=65536)),
                ('lower_threshold', models.IntegerField(default=0)),
            ],
        ),
    ]
