# Generated by Django 2.0.3 on 2019-08-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_no', models.IntegerField(default=0)),
            ],
        ),
    ]
